CREATE TABLE physio_assessments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    player_id UUID NOT NULL,
    therapist_id UUID,
    date_of_assessment DATE NOT NULL,
    diagnosis VARCHAR(500),
    secondary_diagnosis VARCHAR(500),
    medications TEXT,
    recreational_activities VARCHAR(500),
    social_history TEXT,
    current_occupation VARCHAR(200),
    current_complaints TEXT,
    complaints_in_daily_life TEXT,
    complaints_since_when VARCHAR(200),
    frequency_of_complaints VARCHAR(200),
    triggered_by TEXT,
    relieved_by TEXT,
    previous_treatments TEXT,
    previous_therapies TEXT,
    inspection_findings TEXT,
    palpation_findings TEXT,
    pain_intensity INTEGER CHECK (pain_intensity >= 0 AND pain_intensity <= 10),
    pain_description TEXT,
    specific_findings TEXT,
    therapy_goals TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);